name: flash_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2

flutter_native_splash:
  color: "#ffffff"
  image: images/logo.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - images/
